import ReactMarkdown from 'react-markdown';
import { useEffect, useState } from "react";
import type { CreatePost } from "../models";
import { useApi } from "../utilities/useApi";
import { useNavigate, useLocation } from "react-router-dom";
import { useGlobalContext } from "../GlobalContext";
import "../style/post.css"
import Markdown from 'react-markdown';


// Define the shape of each preview item that will be stored in state.
type PreviewFile = {
  // Temporary URL generated by the browser for displaying the file.
  url: string;

  // MIME type of the file (e.g. image/png, video/mp4).
  type: string;
};

export function CreatePost() {
  const { postToEndpoint } = useApi();
  const context = useGlobalContext();
  const navigate = useNavigate();

  const location = useLocation();
  const incomingDraft = location.state?.incomingDraft;

  const [title, setTitle] = useState(incomingDraft?.Title || "");
  const [postBody, setPostBody] = useState(incomingDraft?.Body || "");
  const [isDraft, setIsDraft] = useState(incomingDraft?.isDraft || false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  // State used to store all selected media files for preview.
  const [previews, setPreviews] = useState<PreviewFile[]>([]);

  useEffect(() => {
    return () => {
      previews.forEach((file) => URL.revokeObjectURL(file.url));
    };
  }, [previews]);

  // Runs whenever the user selects files.
  function handleFiles(event: React.ChangeEvent<HTMLInputElement>) {
    // Get the FileList from the input element.
    const files = event.target.files;

    // Exit early if no files were selected.
    if (!files) return;

    // Temporary array to collect valid media files.
    const mediaFiles: PreviewFile[] = [];

    // Convert FileList into a normal array and loop through it.
    Array.from(files).forEach((file) => {
      // Only accept images and videos.
      if (
        file.type.startsWith("image/") ||
        file.type.startsWith("video/")
      ) {
        // Create a temporary browser URL for the file.
        // This lets us display it without uploading it.
        const objectUrl = URL.createObjectURL(file);

        // Store the URL and file type.
        mediaFiles.push({
          url: objectUrl,
          type: file.type,
        });
      }
    });

    // Save all previews into React state.
    // This triggers a re-render.
    setPreviews(mediaFiles);
  }

  //async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
  async function handleSubmit() {
    if (!context?.user) {
      setErrorMessage("A user must be loaded before creating a post.");
      return;
    }

    try {
      setErrorMessage("");
      setIsSubmitting(true);

      const post: CreatePost = {
        Title: title,
        Body: postBody,
        isDraft,
        UserId: context.user.id,
      };

      const response = await postToEndpoint("posts/create", post);

      if (!response || !response.ok) {
        const body = response ? await response.json() : null;
        throw new Error(body?.error ?? "Could not create the post.");
      }

      const body = await response.json();
      const createdPost = body.response;

      navigate(`/ViewPost/${createdPost.id}`);
    } catch (err: any) {
      setErrorMessage(err.message);
      window.alert(err.message);
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <div>
      {/* Form heading */}
      <h1>Create Post</h1>

      {/* Form for creating a new post */}
      <form
        name="fileinfo"
        onSubmit={handleSubmit}
      >
        {/* Title input */}
        <p>
          <label>
            Title
            <input
              type="text"
              name="Title"
              placeholder="Enter title (required)"
              required
              size={32}
              maxLength={64}
              value={title}
              onChange={(event) => setTitle(event.target.value)}
            />
          </label>
        </p>

        {/* Media upload field */}
        <p>
          <label>
            Add media:

            <input
              type="file"

              // Input name used when form is submitted.
              name="media"

              // Allow selecting multiple files.
              multiple

              // Restrict file picker to images and videos.
              accept="image/*,video/*"

              // Run handleFiles whenever files are selected.
              onChange={handleFiles}
            />
          </label>
        </p>

        {/* Preview container */}
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: "12px",
            marginBottom: "16px",
          }}
        >
          {/* Loop through all selected files */}
          {previews.map((file, index) => (
            <div key={index}>
              {/* If the file is an image, render an image preview */}
              {file.type.startsWith("image/") ? (
                <img
                  src={file.url}
                  alt={`Preview ${index}`}
                  style={{
                    width: 200,
                    maxHeight: 200,
                    objectFit: "cover",
                  }}
                />
              ) : (
                /* Otherwise render a video preview */
                <video
                  src={file.url}

                  // Show play/pause controls.
                  controls

                  style={{
                    width: 200,
                    maxHeight: 200,
                  }}
                />
              )}
            </div>
          ))}
        </div>

        {/* Post content textarea */}
        <div>
          <label htmlFor="Post">Post</label>

          <br />

          <textarea
            id="Post"
            name="Body"
            placeholder="Write a Post (required)"
            required
            rows={4}
            maxLength={2000}
            value={postBody}
            onChange={(event) => setPostBody(event.target.value)}
          />
        </div>

        <p>
          <label>
            Save as draft
            <input
              type="checkbox"
              name="isDraft"
              checked={isDraft}
              onChange={(event) => setIsDraft(event.target.checked)}
            />
          </label>
        </p>

        {errorMessage && <p>{errorMessage}</p>}

        {/* Submit button */}
        <p>
          <input
            type="submit"
            value={isDraft ? "Save Draft" : "Publish"}
            disabled={isSubmitting}
          />
        </p>
      </form>
      <h2 style={{ display: 'flex', justifyContent: 'center' }}>Preview</h2>
      <div style={{ padding: '10px', border: '1px solid black' }}>
        <Markdown>{postBody}</Markdown>
      </div>
    </div>

  );
}
