
import { useState } from "react";

// Define the shape of each preview item that will be stored in state.
type PreviewFile = {
  // Temporary URL generated by the browser for displaying the file.
  url: string;

  // MIME type of the file (e.g. image/png, video/mp4).
  type: string;
};

export function CreatePost() {
  // State used to store all selected media files for preview.
  const [previews, setPreviews] = useState<PreviewFile[]>([]);

  // Runs whenever the user selects files.
  function handleFiles(event: React.ChangeEvent<HTMLInputElement>) {
    // Get the FileList from the input element.
    const files = event.target.files;

    // Exit early if no files were selected.
    if (!files) return;

    // Temporary array to collect valid media files.
    const mediaFiles: PreviewFile[] = [];

    // Convert FileList into a normal array and loop through it.
    Array.from(files).forEach((file) => {
      // Only accept images and videos.
      if (
        file.type.startsWith("image/") ||
        file.type.startsWith("video/")
      ) {
        // Create a temporary browser URL for the file.
        // This lets us display it without uploading it.
        const objectUrl = URL.createObjectURL(file);

        // Store the URL and file type.
        mediaFiles.push({
          url: objectUrl,
          type: file.type,
        });
      }
    });

    // Save all previews into React state.
    // This triggers a re-render.
    setPreviews(mediaFiles);
  }

  return (
    <div>
      {/* Form heading */}
      <h1>Create Post</h1>

      {/* Form for creating a new post */}
      <form
        encType="multipart/form-data"
        method="post"
        name="fileinfo"
        id="fileinfo"
      >
        {/* Title input */}
        <p>
          <label>
            Title
            <input
              type="text"
              placeholder="Enter title (required)"
              required
              size={32}
              maxLength={64}
            />
          </label>
        </p>

        {/* Media upload field */}
        <p>
          <label>
            Add media:

            <input
              type="file"

              // Input name used when form is submitted.
              name="media"

              // Allow selecting multiple files.
              multiple

              // Restrict file picker to images and videos.
              accept="image/*,video/*"

              // Run handleFiles whenever files are selected.
              onChange={handleFiles}
            />
          </label>
        </p>

        {/* Preview container */}
        <div
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: "12px",
            marginBottom: "16px",
          }}
        >
          {/* Loop through all selected files */}
          {previews.map((file, index) => (
            <div key={index}>
              {/* If the file is an image, render an image preview */}
              {file.type.startsWith("image/") ? (
                <img
                  src={file.url}
                  alt={`Preview ${index}`}
                  style={{
                    width: 200,
                    maxHeight: 200,
                    objectFit: "cover",
                  }}
                />
              ) : (
                /* Otherwise render a video preview */
                <video
                  src={file.url}

                  // Show play/pause controls.
                  controls

                  style={{
                    width: 200,
                    maxHeight: 200,
                  }}
                />
              )}
            </div>
          ))}
        </div>

        {/* Post content textarea */}
        <div>
          <label htmlFor="Post">Post</label>

          <br />

          <textarea
            id="Post"
            name="Post"
            placeholder="Write a Post (required)"
            required
            rows={4}
            maxLength={2000}
          />
        </div>

        {/* Submit button */}
        <p>
          <input type="submit" value="Publish" />
        </p>
      </form>
    </div>
  );
}